### ISSUE TITLE
[GLOBAL] Setting - 초기셋팅

### ISSUE THREAD

**Issue by tjdud0123** [Motiiv/motiiv-front#1]
## todo
- [x] eslint 및 프리티어 설정
- [x] 불필요 파일 제거 및 컴포넌트 부분 이미지 에셋추가 
- [x] reset css 설정
- [x] 폰트, 파비콘 설정
- [x] 키컬러 셋팅
